image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-vscode.vscode-typescript-tslint-plugin
    - ms-azuretools.vscode-docker
    - eamodio.gitlens 

tasks:
  - init: npm install
    command: npm run start
